/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.ImageIcon;
import logica.CalculadoraImplementacion;
import logica.Otras_Funciones;

/**
 *
 * @author Estudiante
 */
public class CalculadoraForm extends javax.swing.JFrame {

    CalculadoraImplementacion calculadora;
    Otras_Funciones Cadena = new Otras_Funciones();

    /**
     * Creates new form CalculadoraForm
     */
    public CalculadoraForm() {
        initComponents();
        calculadora = new CalculadoraImplementacion();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono2.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Display1 = new javax.swing.JTextField();
        Numero_10 = new javax.swing.JButton();
        Numero_11 = new javax.swing.JButton();
        Numero_12 = new javax.swing.JButton();
        Numero_13 = new javax.swing.JButton();
        Numero_14 = new javax.swing.JButton();
        Numero_15 = new javax.swing.JButton();
        Numero_16 = new javax.swing.JButton();
        Numero_17 = new javax.swing.JButton();
        Numero_18 = new javax.swing.JButton();
        Numero_19 = new javax.swing.JButton();
        Suma1 = new javax.swing.JButton();
        Resta1 = new javax.swing.JButton();
        Multiplicacion1 = new javax.swing.JButton();
        Division1 = new javax.swing.JButton();
        Boton_Igual1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Display_A = new javax.swing.JTextField();
        Numero_9 = new javax.swing.JButton();
        Numero_0 = new javax.swing.JButton();
        Suma = new javax.swing.JButton();
        Resta = new javax.swing.JButton();
        Multiplicacion = new javax.swing.JButton();
        Division = new javax.swing.JButton();
        Boton_Igual = new javax.swing.JButton();
        Numero_1 = new javax.swing.JButton();
        Numero_2 = new javax.swing.JButton();
        Numero_3 = new javax.swing.JButton();
        Numero_4 = new javax.swing.JButton();
        Numero_5 = new javax.swing.JButton();
        Numero_6 = new javax.swing.JButton();
        Numero_7 = new javax.swing.JButton();
        Numero_8 = new javax.swing.JButton();
        Display_B = new javax.swing.JTextField();
        CE = new javax.swing.JButton();
        C = new javax.swing.JButton();
        signo = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        Coma = new javax.swing.JButton();
        MC = new javax.swing.JButton();
        MR = new javax.swing.JButton();
        MS = new javax.swing.JButton();
        Mmas = new javax.swing.JButton();
        Mmenos = new javax.swing.JButton();
        Raiz = new javax.swing.JButton();
        inversa = new javax.swing.JButton();
        Porcentaje = new javax.swing.JButton();
        elevar = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Display1.setEditable(false);
        Display1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Display1ActionPerformed(evt);
            }
        });

        Numero_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Normal.png"))); // NOI18N
        Numero_10.setBorder(null);
        Numero_10.setBorderPainted(false);
        Numero_10.setContentAreaFilled(false);
        Numero_10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Click.png"))); // NOI18N
        Numero_10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Mouse.png"))); // NOI18N
        Numero_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_10ActionPerformed(evt);
            }
        });

        Numero_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2_Normal.png"))); // NOI18N
        Numero_11.setBorder(null);
        Numero_11.setBorderPainted(false);
        Numero_11.setContentAreaFilled(false);
        Numero_11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2_Click.png"))); // NOI18N
        Numero_11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2_Mouse.png"))); // NOI18N

        Numero_12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3_Normal.png"))); // NOI18N
        Numero_12.setBorder(null);
        Numero_12.setBorderPainted(false);
        Numero_12.setContentAreaFilled(false);
        Numero_12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3_Click.png"))); // NOI18N
        Numero_12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3_Mouse.png"))); // NOI18N

        Numero_13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4_Normal.png"))); // NOI18N
        Numero_13.setBorder(null);
        Numero_13.setBorderPainted(false);
        Numero_13.setContentAreaFilled(false);
        Numero_13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4_Click.png"))); // NOI18N
        Numero_13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4_Mouse.png"))); // NOI18N

        Numero_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5_Normal.png"))); // NOI18N
        Numero_14.setBorder(null);
        Numero_14.setBorderPainted(false);
        Numero_14.setContentAreaFilled(false);
        Numero_14.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5_Click.png"))); // NOI18N
        Numero_14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5_Mouse.png"))); // NOI18N

        Numero_15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6_Normal.png"))); // NOI18N
        Numero_15.setBorder(null);
        Numero_15.setBorderPainted(false);
        Numero_15.setContentAreaFilled(false);
        Numero_15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6_Click.png"))); // NOI18N
        Numero_15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6_Mouse.png"))); // NOI18N

        Numero_16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7_Normal.png"))); // NOI18N
        Numero_16.setBorder(null);
        Numero_16.setBorderPainted(false);
        Numero_16.setContentAreaFilled(false);
        Numero_16.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7_Click.png"))); // NOI18N
        Numero_16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7_Mouse.png"))); // NOI18N

        Numero_17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8_Normal.png"))); // NOI18N
        Numero_17.setBorder(null);
        Numero_17.setBorderPainted(false);
        Numero_17.setContentAreaFilled(false);
        Numero_17.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8_Click.png"))); // NOI18N
        Numero_17.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8_Mouse.png"))); // NOI18N

        Numero_18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9_Normal.png"))); // NOI18N
        Numero_18.setBorder(null);
        Numero_18.setBorderPainted(false);
        Numero_18.setContentAreaFilled(false);
        Numero_18.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9_Click.png"))); // NOI18N
        Numero_18.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9_Mouse.png"))); // NOI18N

        Numero_19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0_Normal.png"))); // NOI18N
        Numero_19.setBorder(null);
        Numero_19.setBorderPainted(false);
        Numero_19.setContentAreaFilled(false);
        Numero_19.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0_Click.png"))); // NOI18N
        Numero_19.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0_Mouse.png"))); // NOI18N

        Suma1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/+_Normal.png"))); // NOI18N
        Suma1.setBorder(null);
        Suma1.setBorderPainted(false);
        Suma1.setContentAreaFilled(false);
        Suma1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/+_Click.png"))); // NOI18N
        Suma1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/+_Mouse.png"))); // NOI18N

        Resta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-_Normal.png"))); // NOI18N
        Resta1.setBorder(null);
        Resta1.setBorderPainted(false);
        Resta1.setContentAreaFilled(false);
        Resta1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-_Click.png"))); // NOI18N
        Resta1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-_Mouse.png"))); // NOI18N
        Resta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resta1ActionPerformed(evt);
            }
        });

        Multiplicacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x_Normal.png"))); // NOI18N
        Multiplicacion1.setBorder(null);
        Multiplicacion1.setBorderPainted(false);
        Multiplicacion1.setContentAreaFilled(false);
        Multiplicacion1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x_Click.png"))); // NOI18N
        Multiplicacion1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x_Mouse.png"))); // NOI18N

        Division1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/d_Normal.png"))); // NOI18N
        Division1.setBorder(null);
        Division1.setBorderPainted(false);
        Division1.setContentAreaFilled(false);
        Division1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/d_Click.png"))); // NOI18N
        Division1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/d_Mouse.png"))); // NOI18N

        Boton_Igual1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/=_Normal.png"))); // NOI18N
        Boton_Igual1.setBorder(null);
        Boton_Igual1.setBorderPainted(false);
        Boton_Igual1.setContentAreaFilled(false);
        Boton_Igual1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/=_Click.png"))); // NOI18N
        Boton_Igual1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/=_Mouse.png"))); // NOI18N
        Boton_Igual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Igual1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Display1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(Numero_10)
                        .addGap(6, 6, 6)
                        .addComponent(Numero_11)
                        .addGap(6, 6, 6)
                        .addComponent(Numero_12))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(Numero_13)
                        .addGap(6, 6, 6)
                        .addComponent(Numero_14)
                        .addGap(6, 6, 6)
                        .addComponent(Numero_15))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(Numero_16)
                        .addGap(6, 6, 6)
                        .addComponent(Numero_17)
                        .addGap(6, 6, 6)
                        .addComponent(Numero_18))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(Numero_19)
                        .addGap(6, 6, 6)
                        .addComponent(Suma1)
                        .addGap(6, 6, 6)
                        .addComponent(Resta1))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(Multiplicacion1)
                        .addGap(6, 6, 6)
                        .addComponent(Division1)
                        .addGap(6, 6, 6)
                        .addComponent(Boton_Igual1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Display1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numero_10)
                    .addComponent(Numero_11)
                    .addComponent(Numero_12))
                .addGap(6, 6, 6)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numero_13)
                    .addComponent(Numero_14)
                    .addComponent(Numero_15))
                .addGap(6, 6, 6)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numero_16)
                    .addComponent(Numero_17)
                    .addComponent(Numero_18))
                .addGap(6, 6, 6)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numero_19)
                    .addComponent(Suma1)
                    .addComponent(Resta1))
                .addGap(6, 6, 6)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Multiplicacion1)
                    .addComponent(Division1)
                    .addComponent(Boton_Igual1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA");
        setBackground(new java.awt.Color(236, 236, 236));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(236, 236, 236));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setFocusable(false);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        Display_A.setEditable(false);
        Display_A.setBackground(new java.awt.Color(236, 236, 236));
        Display_A.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        Display_A.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display_A.setBorder(null);
        Display_A.setFocusable(false);
        Display_A.setRequestFocusEnabled(false);
        Display_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Display_AActionPerformed(evt);
            }
        });

        Numero_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9_Normal.png"))); // NOI18N
        Numero_9.setBorder(null);
        Numero_9.setBorderPainted(false);
        Numero_9.setContentAreaFilled(false);
        Numero_9.setFocusable(false);
        Numero_9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9_Click.png"))); // NOI18N
        Numero_9.setRequestFocusEnabled(false);
        Numero_9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9_Mouse.png"))); // NOI18N
        Numero_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_9ActionPerformed(evt);
            }
        });

        Numero_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0_Normal.png"))); // NOI18N
        Numero_0.setBorder(null);
        Numero_0.setBorderPainted(false);
        Numero_0.setContentAreaFilled(false);
        Numero_0.setFocusable(false);
        Numero_0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0_Click.png"))); // NOI18N
        Numero_0.setRequestFocusEnabled(false);
        Numero_0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0_Mouse.png"))); // NOI18N
        Numero_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_0ActionPerformed(evt);
            }
        });

        Suma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/+_Normal.png"))); // NOI18N
        Suma.setBorder(null);
        Suma.setBorderPainted(false);
        Suma.setContentAreaFilled(false);
        Suma.setFocusable(false);
        Suma.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/+_Click.png"))); // NOI18N
        Suma.setRequestFocusEnabled(false);
        Suma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/+_Mouse.png"))); // NOI18N
        Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActionPerformed(evt);
            }
        });

        Resta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-_Normal.png"))); // NOI18N
        Resta.setBorder(null);
        Resta.setBorderPainted(false);
        Resta.setContentAreaFilled(false);
        Resta.setFocusable(false);
        Resta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-_Click.png"))); // NOI18N
        Resta.setRequestFocusEnabled(false);
        Resta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-_Mouse.png"))); // NOI18N
        Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaActionPerformed(evt);
            }
        });

        Multiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x_Normal.png"))); // NOI18N
        Multiplicacion.setBorder(null);
        Multiplicacion.setBorderPainted(false);
        Multiplicacion.setContentAreaFilled(false);
        Multiplicacion.setFocusable(false);
        Multiplicacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x_Click.png"))); // NOI18N
        Multiplicacion.setRequestFocusEnabled(false);
        Multiplicacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x_Mouse.png"))); // NOI18N
        Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionActionPerformed(evt);
            }
        });

        Division.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/d_Normal.png"))); // NOI18N
        Division.setBorder(null);
        Division.setBorderPainted(false);
        Division.setContentAreaFilled(false);
        Division.setFocusable(false);
        Division.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/d_Click.png"))); // NOI18N
        Division.setRequestFocusEnabled(false);
        Division.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/d_Mouse.png"))); // NOI18N
        Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionActionPerformed(evt);
            }
        });

        Boton_Igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/=_Normal.png"))); // NOI18N
        Boton_Igual.setBorder(null);
        Boton_Igual.setBorderPainted(false);
        Boton_Igual.setContentAreaFilled(false);
        Boton_Igual.setFocusable(false);
        Boton_Igual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/=_Click.png"))); // NOI18N
        Boton_Igual.setRequestFocusEnabled(false);
        Boton_Igual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/=_Mouse.png"))); // NOI18N
        Boton_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_IgualActionPerformed(evt);
            }
        });

        Numero_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Normal.png"))); // NOI18N
        Numero_1.setBorder(null);
        Numero_1.setBorderPainted(false);
        Numero_1.setContentAreaFilled(false);
        Numero_1.setFocusable(false);
        Numero_1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Click.png"))); // NOI18N
        Numero_1.setRequestFocusEnabled(false);
        Numero_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Mouse.png"))); // NOI18N
        Numero_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_1ActionPerformed(evt);
            }
        });

        Numero_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2_Normal.png"))); // NOI18N
        Numero_2.setBorder(null);
        Numero_2.setBorderPainted(false);
        Numero_2.setContentAreaFilled(false);
        Numero_2.setFocusable(false);
        Numero_2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2_Click.png"))); // NOI18N
        Numero_2.setRequestFocusEnabled(false);
        Numero_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2_Mouse.png"))); // NOI18N
        Numero_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_2ActionPerformed(evt);
            }
        });

        Numero_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3_Normal.png"))); // NOI18N
        Numero_3.setBorder(null);
        Numero_3.setBorderPainted(false);
        Numero_3.setContentAreaFilled(false);
        Numero_3.setFocusable(false);
        Numero_3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3_Click.png"))); // NOI18N
        Numero_3.setRequestFocusEnabled(false);
        Numero_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3_Mouse.png"))); // NOI18N
        Numero_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_3ActionPerformed(evt);
            }
        });

        Numero_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4_Normal.png"))); // NOI18N
        Numero_4.setBorder(null);
        Numero_4.setBorderPainted(false);
        Numero_4.setContentAreaFilled(false);
        Numero_4.setFocusable(false);
        Numero_4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4_Click.png"))); // NOI18N
        Numero_4.setRequestFocusEnabled(false);
        Numero_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4_Mouse.png"))); // NOI18N
        Numero_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_4ActionPerformed(evt);
            }
        });

        Numero_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5_Normal.png"))); // NOI18N
        Numero_5.setBorder(null);
        Numero_5.setBorderPainted(false);
        Numero_5.setContentAreaFilled(false);
        Numero_5.setFocusable(false);
        Numero_5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5_Click.png"))); // NOI18N
        Numero_5.setRequestFocusEnabled(false);
        Numero_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5_Mouse.png"))); // NOI18N
        Numero_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_5ActionPerformed(evt);
            }
        });

        Numero_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6_Normal.png"))); // NOI18N
        Numero_6.setBorder(null);
        Numero_6.setBorderPainted(false);
        Numero_6.setContentAreaFilled(false);
        Numero_6.setFocusable(false);
        Numero_6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6_Click.png"))); // NOI18N
        Numero_6.setRequestFocusEnabled(false);
        Numero_6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6_Mouse.png"))); // NOI18N
        Numero_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_6ActionPerformed(evt);
            }
        });

        Numero_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7_Normal.png"))); // NOI18N
        Numero_7.setBorder(null);
        Numero_7.setBorderPainted(false);
        Numero_7.setContentAreaFilled(false);
        Numero_7.setFocusable(false);
        Numero_7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7_Click.png"))); // NOI18N
        Numero_7.setRequestFocusEnabled(false);
        Numero_7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7_Mouse.png"))); // NOI18N
        Numero_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_7ActionPerformed(evt);
            }
        });

        Numero_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8_Normal.png"))); // NOI18N
        Numero_8.setBorder(null);
        Numero_8.setBorderPainted(false);
        Numero_8.setContentAreaFilled(false);
        Numero_8.setFocusable(false);
        Numero_8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8_Click.png"))); // NOI18N
        Numero_8.setRequestFocusEnabled(false);
        Numero_8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8_Mouse.png"))); // NOI18N
        Numero_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_8ActionPerformed(evt);
            }
        });

        Display_B.setEditable(false);
        Display_B.setBackground(new java.awt.Color(236, 236, 236));
        Display_B.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        Display_B.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display_B.setBorder(null);
        Display_B.setFocusable(false);
        Display_B.setRequestFocusEnabled(false);
        Display_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Display_BActionPerformed(evt);
            }
        });

        CE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/CE_Normal.png"))); // NOI18N
        CE.setBorder(null);
        CE.setBorderPainted(false);
        CE.setContentAreaFilled(false);
        CE.setFocusable(false);
        CE.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/CE_Click.png"))); // NOI18N
        CE.setRequestFocusEnabled(false);
        CE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/CE_Mouse.png"))); // NOI18N
        CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEActionPerformed(evt);
            }
        });

        C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/C_Normal.png"))); // NOI18N
        C.setBorder(null);
        C.setBorderPainted(false);
        C.setContentAreaFilled(false);
        C.setFocusable(false);
        C.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/C_Click.png"))); // NOI18N
        C.setRequestFocusEnabled(false);
        C.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/C_Mouse.png"))); // NOI18N
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        signo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/signo_Normal.png"))); // NOI18N
        signo.setBorder(null);
        signo.setBorderPainted(false);
        signo.setContentAreaFilled(false);
        signo.setFocusable(false);
        signo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/signo_Click.png"))); // NOI18N
        signo.setRequestFocusEnabled(false);
        signo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/signo_Mouse.png"))); // NOI18N
        signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoActionPerformed(evt);
            }
        });

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/eliminar_Normal.png"))); // NOI18N
        eliminar.setBorder(null);
        eliminar.setBorderPainted(false);
        eliminar.setContentAreaFilled(false);
        eliminar.setFocusable(false);
        eliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/eliminar_Click.png"))); // NOI18N
        eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/eliminar_Mouse.png"))); // NOI18N
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        eliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eliminarKeyPressed(evt);
            }
        });

        Coma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/coma_Normal.png"))); // NOI18N
        Coma.setBorder(null);
        Coma.setBorderPainted(false);
        Coma.setContentAreaFilled(false);
        Coma.setFocusable(false);
        Coma.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/coma_Click.png"))); // NOI18N
        Coma.setRequestFocusEnabled(false);
        Coma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/coma_Mouse.png"))); // NOI18N
        Coma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComaActionPerformed(evt);
            }
        });

        MC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/MC_Normal.png"))); // NOI18N
        MC.setBorder(null);
        MC.setBorderPainted(false);
        MC.setContentAreaFilled(false);
        MC.setFocusable(false);
        MC.setPreferredSize(new java.awt.Dimension(58, 35));
        MC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/MC_Click.png"))); // NOI18N
        MC.setRequestFocusEnabled(false);
        MC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/MC_Mouse.png"))); // NOI18N
        MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCActionPerformed(evt);
            }
        });

        MR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/MR_Normal.png"))); // NOI18N
        MR.setBorder(null);
        MR.setBorderPainted(false);
        MR.setContentAreaFilled(false);
        MR.setFocusable(false);
        MR.setPreferredSize(new java.awt.Dimension(58, 35));
        MR.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/MR_Click.png"))); // NOI18N
        MR.setRequestFocusEnabled(false);
        MR.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/MR_Mouse.png"))); // NOI18N
        MR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRActionPerformed(evt);
            }
        });

        MS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/MS_Normal.png"))); // NOI18N
        MS.setBorder(null);
        MS.setBorderPainted(false);
        MS.setContentAreaFilled(false);
        MS.setFocusable(false);
        MS.setPreferredSize(new java.awt.Dimension(58, 35));
        MS.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/MS_Click.png"))); // NOI18N
        MS.setRequestFocusEnabled(false);
        MS.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/MS_Mouse.png"))); // NOI18N
        MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSActionPerformed(evt);
            }
        });

        Mmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/M+_Normal.png"))); // NOI18N
        Mmas.setBorder(null);
        Mmas.setBorderPainted(false);
        Mmas.setContentAreaFilled(false);
        Mmas.setFocusable(false);
        Mmas.setPreferredSize(new java.awt.Dimension(58, 35));
        Mmas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/M+_Click.png"))); // NOI18N
        Mmas.setRequestFocusEnabled(false);
        Mmas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/M+_Mouse.png"))); // NOI18N
        Mmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MmasActionPerformed(evt);
            }
        });

        Mmenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/M-_Normal.png"))); // NOI18N
        Mmenos.setBorder(null);
        Mmenos.setBorderPainted(false);
        Mmenos.setContentAreaFilled(false);
        Mmenos.setFocusable(false);
        Mmenos.setPreferredSize(new java.awt.Dimension(58, 35));
        Mmenos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/M-_Click.png"))); // NOI18N
        Mmenos.setRequestFocusEnabled(false);
        Mmenos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/M-_Mouse.png"))); // NOI18N
        Mmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MmenosActionPerformed(evt);
            }
        });

        Raiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/raiz_Normal.png"))); // NOI18N
        Raiz.setBorder(null);
        Raiz.setBorderPainted(false);
        Raiz.setContentAreaFilled(false);
        Raiz.setFocusable(false);
        Raiz.setPreferredSize(new java.awt.Dimension(75, 45));
        Raiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/raiz_Click.png"))); // NOI18N
        Raiz.setRequestFocusEnabled(false);
        Raiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/raiz_Mouse.png"))); // NOI18N
        Raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaizActionPerformed(evt);
            }
        });

        inversa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/inversa_Normal.png"))); // NOI18N
        inversa.setBorder(null);
        inversa.setBorderPainted(false);
        inversa.setContentAreaFilled(false);
        inversa.setFocusable(false);
        inversa.setPreferredSize(new java.awt.Dimension(75, 45));
        inversa.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/inversa_Click.png"))); // NOI18N
        inversa.setRequestFocusEnabled(false);
        inversa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/inversa_Mouse.png"))); // NOI18N
        inversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversaActionPerformed(evt);
            }
        });

        Porcentaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/porcentaje_Normal.png"))); // NOI18N
        Porcentaje.setBorder(null);
        Porcentaje.setBorderPainted(false);
        Porcentaje.setContentAreaFilled(false);
        Porcentaje.setFocusable(false);
        Porcentaje.setPreferredSize(new java.awt.Dimension(75, 45));
        Porcentaje.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/porcentaje_Click.png"))); // NOI18N
        Porcentaje.setRequestFocusEnabled(false);
        Porcentaje.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/porcentaje_Mouse.png"))); // NOI18N
        Porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorcentajeActionPerformed(evt);
            }
        });

        elevar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/cuadrado_Normal.png"))); // NOI18N
        elevar.setBorder(null);
        elevar.setBorderPainted(false);
        elevar.setContentAreaFilled(false);
        elevar.setFocusable(false);
        elevar.setPreferredSize(new java.awt.Dimension(75, 45));
        elevar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/cuadrado_Click.png"))); // NOI18N
        elevar.setRequestFocusEnabled(false);
        elevar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/cuadrado_Mouse.png"))); // NOI18N
        elevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Display_B)
                    .addComponent(Display_A)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Numero_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Suma))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Division))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(signo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero_0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Coma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton_Igual))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Numero_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero_8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero_9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Multiplicacion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Numero_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Resta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mmenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(elevar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inversa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(Display_A, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Display_B, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mmenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(elevar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inversa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Division, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Numero_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numero_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numero_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Multiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Numero_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numero_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numero_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Resta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Numero_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numero_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numero_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numero_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Coma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_Igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_IgualActionPerformed
        // TODO add your handling code here:
        double Operando_B = Double.parseDouble(Display_B.getText());
        calculadora.setOperandoB(Operando_B);
        Display_B.setText(" " + calculadora.getResultado());
        Display_A.setText(calculadora.getExpresion());
    }//GEN-LAST:event_Boton_IgualActionPerformed

    private void Display_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Display_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Display_AActionPerformed

    private void Numero_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_1ActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Display_B.getText() + "1");
    }//GEN-LAST:event_Numero_1ActionPerformed

    private void RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaActionPerformed
        // TODO add your handling code here:
        int Estado = calculadora.getEstado();
        switch (Estado) {
            case 0:
                double Operando_A = Double.parseDouble(Display_B.getText());
                calculadora.setOperandoA(Operando_A);
                calculadora.setOperador('-');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
            case 1:
                calculadora.setOperador('-');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
            case 2:
                double Operando_B = Double.parseDouble(Display_B.getText());
                calculadora.setOperandoB(Operando_B);
                calculadora.getResultado();
                calculadora.setOperador('-');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
        }
    }//GEN-LAST:event_RestaActionPerformed

    private void Display1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Display1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Display1ActionPerformed

    private void Numero_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Numero_10ActionPerformed

    private void Resta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resta1ActionPerformed

    private void Boton_Igual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Igual1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Igual1ActionPerformed

    private void Numero_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_3ActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Display_B.getText() + "3");
    }//GEN-LAST:event_Numero_3ActionPerformed

    private void Display_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Display_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Display_BActionPerformed

    private void Numero_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_2ActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Display_B.getText() + "2");
    }//GEN-LAST:event_Numero_2ActionPerformed

    private void Numero_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_4ActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Display_B.getText() + "4");
    }//GEN-LAST:event_Numero_4ActionPerformed

    private void Numero_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_5ActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Display_B.getText() + "5");
    }//GEN-LAST:event_Numero_5ActionPerformed

    private void Numero_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_6ActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Display_B.getText() + "6");
    }//GEN-LAST:event_Numero_6ActionPerformed

    private void Numero_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_7ActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Display_B.getText() + "7");
    }//GEN-LAST:event_Numero_7ActionPerformed

    private void Numero_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_8ActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Display_B.getText() + "8");
    }//GEN-LAST:event_Numero_8ActionPerformed

    private void Numero_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_9ActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Display_B.getText() + "9");
    }//GEN-LAST:event_Numero_9ActionPerformed

    private void Numero_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_0ActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Display_B.getText() + "0");
    }//GEN-LAST:event_Numero_0ActionPerformed

    private void SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaActionPerformed
        // TODO add your handling code here:
        int Estado = calculadora.getEstado();
        switch (Estado) {
            case 0:
                double Operando_A = Double.parseDouble(Display_B.getText());
                calculadora.setOperandoA(Operando_A);
                calculadora.setOperador('+');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
            case 1:
                calculadora.setOperador('+');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
            case 2:
                double Operando_B = Double.parseDouble(Display_B.getText());
                calculadora.setOperandoB(Operando_B);
                calculadora.getResultado();
                calculadora.setOperador('+');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
        }
    }//GEN-LAST:event_SumaActionPerformed

    private void MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionActionPerformed
        // TODO add your handling code here:
        int Estado = calculadora.getEstado();
        switch (Estado) {
            case 0:
                double Operando_A = Double.parseDouble(Display_B.getText());
                calculadora.setOperandoA(Operando_A);
                calculadora.setOperador('*');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
            case 1:
                calculadora.setOperador('*');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
            case 2:
                double Operando_B = Double.parseDouble(Display_B.getText());
                calculadora.setOperandoB(Operando_B);
                calculadora.getResultado();
                calculadora.setOperador('*');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
        }
    }//GEN-LAST:event_MultiplicacionActionPerformed

    private void DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionActionPerformed
        // TODO add your handling code here:
        int Estado = calculadora.getEstado();
        switch (Estado) {
            case 0:
                double Operando_A = Double.parseDouble(Display_B.getText());
                calculadora.setOperandoA(Operando_A);
                calculadora.setOperador('/');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
            case 1:
                calculadora.setOperador('/');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
            case 2:
                double Operando_B = Double.parseDouble(Display_B.getText());
                calculadora.setOperandoB(Operando_B);
                calculadora.getResultado();
                calculadora.setOperador('/');
                Display_A.setText(calculadora.getExpresion());
                Display_B.setText("");
                break;
        }
    }//GEN-LAST:event_DivisionActionPerformed

    private void CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEActionPerformed
        // TODO add your handling code here:
        if (!Display_B.getText().equals("")) {
            Display_B.setText("");
        }
    }//GEN-LAST:event_CEActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        calculadora = new CalculadoraImplementacion();
        Display_B.setText("");
        Display_A.setText("");
    }//GEN-LAST:event_CActionPerformed

    private void signoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoActionPerformed
        // TODO add your handling code here:
        Display_B.setText(Cadena.cambiarSigno(Display_B.getText()));
    }//GEN-LAST:event_signoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        if (!Display_B.getText().equals("")) {
            Display_B.setText(Cadena.convertirCadena(Display_B.getText()));
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void ComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComaActionPerformed
        // TODO add your handling code here:

        if (!Cadena.escanearComa(Display_B.getText())) {
            Display_B.setText(Display_B.getText() + ".");
        }
    }//GEN-LAST:event_ComaActionPerformed

    private void MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCActionPerformed
        // TODO add your handling code here:
        calculadora.setMemoria(calculadora.getMemoria(), '-');
        Display_B.setText("");
    }//GEN-LAST:event_MCActionPerformed

    private void MmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MmasActionPerformed
        // TODO add your handling code here:
        double temp = Double.parseDouble(Display_B.getText());
        calculadora.setMemoria(temp, '+');
    }//GEN-LAST:event_MmasActionPerformed

    private void MRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRActionPerformed
        // TODO add your handling code here:
        if (calculadora.getMemoria() != 0) {
            Display_B.setText("" + calculadora.getMemoria());
        }
    }//GEN-LAST:event_MRActionPerformed

    private void MmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MmenosActionPerformed
        // TODO add your handling code here:
        double temp = Double.parseDouble(Display_B.getText());
        calculadora.setMemoria(temp, '-');
    }//GEN-LAST:event_MmenosActionPerformed

    private void MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSActionPerformed
        // TODO add your handling code here:
        double temp = Double.parseDouble(Display_B.getText());
        calculadora.setMemoria(calculadora.getMemoria(), '-');
        calculadora.setMemoria(temp, '+');
    }//GEN-LAST:event_MSActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.out.println(evt.getKeyCode());
        if ((evt.getKeyCode() >= 48 && evt.getKeyCode() <= 57) || (evt.getKeyCode() >= 96 && evt.getKeyCode() <= 105)) {
            Display_B.setText(Display_B.getText() + evt.getKeyChar());
        }
        if (evt.getKeyCode() == 8) {
            if (!Display_B.getText().equals("")) {
                Display_B.setText(Cadena.convertirCadena(Display_B.getText()));
            }
        }
        if (evt.getKeyChar() == '+') {
            int Estado = calculadora.getEstado();
            switch (Estado) {
                case 0:
                    double Operando_A = Double.parseDouble(Display_B.getText());
                    calculadora.setOperandoA(Operando_A);
                    calculadora.setOperador('+');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
                case 1:
                    calculadora.setOperador('+');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
                case 2:
                    double Operando_B = Double.parseDouble(Display_B.getText());
                    calculadora.setOperandoB(Operando_B);
                    calculadora.getResultado();
                    calculadora.setOperador('+');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
            }
        }
        if (evt.getKeyChar() == '-') {
            int Estado = calculadora.getEstado();
            switch (Estado) {
                case 0:
                    double Operando_A = Double.parseDouble(Display_B.getText());
                    calculadora.setOperandoA(Operando_A);
                    calculadora.setOperador('-');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
                case 1:
                    calculadora.setOperador('-');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
                case 2:
                    double Operando_B = Double.parseDouble(Display_B.getText());
                    calculadora.setOperandoB(Operando_B);
                    calculadora.getResultado();
                    calculadora.setOperador('-');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
            }
        }
        if (evt.getKeyChar() == '/') {
            int Estado = calculadora.getEstado();
            switch (Estado) {
                case 0:
                    double Operando_A = Double.parseDouble(Display_B.getText());
                    calculadora.setOperandoA(Operando_A);
                    calculadora.setOperador('/');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
                case 1:
                    calculadora.setOperador('/');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
                case 2:
                    double Operando_B = Double.parseDouble(Display_B.getText());
                    calculadora.setOperandoB(Operando_B);
                    calculadora.getResultado();
                    calculadora.setOperador('/');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
            }
        }
        if (evt.getKeyChar() == '*') {
            int Estado = calculadora.getEstado();
            switch (Estado) {
                case 0:
                    double Operando_A = Double.parseDouble(Display_B.getText());
                    calculadora.setOperandoA(Operando_A);
                    calculadora.setOperador('*');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
                case 1:
                    calculadora.setOperador('*');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
                case 2:
                    double Operando_B = Double.parseDouble(Display_B.getText());
                    calculadora.setOperandoB(Operando_B);
                    calculadora.getResultado();
                    calculadora.setOperador('*');
                    Display_A.setText(calculadora.getExpresion());
                    Display_B.setText("");
                    break;
            }
        }
        if (evt.getKeyCode() == 10) {
            double Operando_B = Double.parseDouble(Display_B.getText());
            calculadora.setOperandoB(Operando_B);
            Display_B.setText(" " + calculadora.getResultado());
            Display_A.setText(calculadora.getExpresion());
        }
        if (evt.getKeyCode() == 127) {
            calculadora = new CalculadoraImplementacion();
            Display_B.setText("");
            Display_A.setText("");
        }
    }//GEN-LAST:event_formKeyPressed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code he
    }//GEN-LAST:event_formFocusLost

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed

    }//GEN-LAST:event_jPanel1KeyPressed

    private void eliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eliminarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 8) {
            if (!Display_B.getText().equals("")) {
                Display_B.setText(Cadena.convertirCadena(Display_B.getText()));
            }
        }
    }//GEN-LAST:event_eliminarKeyPressed

    private void elevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevarActionPerformed
        // TODO add your handling code here:
        if (!Display_B.getText().equals("")) {
            double elevar = Double.parseDouble(Display_B.getText());
            elevar = elevar * elevar;
            Display_B.setText("" + elevar);
        }
    }//GEN-LAST:event_elevarActionPerformed

    private void inversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inversaActionPerformed
        // TODO add your handling code here:
        if (!Display_B.getText().equals("")) {
            double inversa = Double.parseDouble(Display_B.getText());
            inversa = 1 / inversa;
            Display_B.setText("" + inversa);
        }
    }//GEN-LAST:event_inversaActionPerformed

    private void RaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaizActionPerformed
        // TODO add your handling code here:
        if (!Display_B.getText().equals("")) {
            double raiz = Double.parseDouble(Display_B.getText());
            raiz = (double) Math.sqrt(raiz);
            Display_B.setText("" + raiz);
        }
    }//GEN-LAST:event_RaizActionPerformed

    private void PorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcentajeActionPerformed
        // TODO add your handling code here:
        if (calculadora.getEstado() == 2 && !Display_B.getText().equals("")) {
            double porcentaje = Double.parseDouble(Display_B.getText());
            porcentaje = porcentaje / 100;
            calculadora.setOperandoB(porcentaje);
            Display_B.setText(" " + calculadora.getResultado());
            Display_A.setText(calculadora.getExpresion());
        }
    }//GEN-LAST:event_PorcentajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Igual;
    private javax.swing.JButton Boton_Igual1;
    private javax.swing.JButton C;
    private javax.swing.JButton CE;
    private javax.swing.JButton Coma;
    private javax.swing.JTextField Display1;
    private javax.swing.JTextField Display_A;
    private javax.swing.JTextField Display_B;
    private javax.swing.JButton Division;
    private javax.swing.JButton Division1;
    private javax.swing.JButton MC;
    private javax.swing.JButton MR;
    private javax.swing.JButton MS;
    private javax.swing.JButton Mmas;
    private javax.swing.JButton Mmenos;
    private javax.swing.JButton Multiplicacion;
    private javax.swing.JButton Multiplicacion1;
    private javax.swing.JButton Numero_0;
    private javax.swing.JButton Numero_1;
    private javax.swing.JButton Numero_10;
    private javax.swing.JButton Numero_11;
    private javax.swing.JButton Numero_12;
    private javax.swing.JButton Numero_13;
    private javax.swing.JButton Numero_14;
    private javax.swing.JButton Numero_15;
    private javax.swing.JButton Numero_16;
    private javax.swing.JButton Numero_17;
    private javax.swing.JButton Numero_18;
    private javax.swing.JButton Numero_19;
    private javax.swing.JButton Numero_2;
    private javax.swing.JButton Numero_3;
    private javax.swing.JButton Numero_4;
    private javax.swing.JButton Numero_5;
    private javax.swing.JButton Numero_6;
    private javax.swing.JButton Numero_7;
    private javax.swing.JButton Numero_8;
    private javax.swing.JButton Numero_9;
    private javax.swing.JButton Porcentaje;
    private javax.swing.JButton Raiz;
    private javax.swing.JButton Resta;
    private javax.swing.JButton Resta1;
    private javax.swing.JButton Suma;
    private javax.swing.JButton Suma1;
    private javax.swing.JButton elevar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton inversa;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton signo;
    // End of variables declaration//GEN-END:variables

}
